---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: pages
  label: Páginas
  create: all
  match: "**/*.md"
- type: directory
  path: posts
  label: Noticias
  create: all
  match: "**/*.md"
  templates:
  - noticia
upload_dir: images/uploads
public_path: "/images/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
