---
new_page_extension: md
auto_deploy: false
admin_path: "/files/admin/"
webhook_url: 
sections:
- type: directory
  path: pages
  label: Páginas
  create: all
  match: "**/*.md"
  templates:
  - pagina
- type: directory
  path: fallos
  label: Fallos
  create: all
  match: "**/*.md"
  templates:
  - pagina
- type: directory
  path: posts
  label: Noticias
  create: all
  match: "**/*.md"
  templates:
  - noticia
upload_dir: images/uploads
public_path: "/images/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: "/nikola/output"
  install_dependencies_command: pip3 install nikola[extras]
  preview_docker_image: dragas/nikola
  mount_path: "/nikola"
  working_dir: "/nikola"
  instant_preview_command: nikola auto
