name: Nikola Publish

on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Nikola
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --upgrade -r requirements.txt
      - name: Build and deploy Nikola
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "Roberto Alsina"
          echo "FIXING TOCS"
          grep TOC pages/*md
          echo "-------------"
          echo sed -i 's/\\\\\[TOC\\\]/[TOC]/g' pages/*md posts/*md
          grep TOC pages/*md
          echo "-------------"
          nikola build
          nikola github_deploy -m "Published with Github Actions"
